# Generated by Django 4.2 on 2024-05-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Бренд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Не задано', 'Не задано'), ('Мужские', 'Мужские'), ('Женские', 'Женские'), ('Унисекс', 'Унисекс')], max_length=255, unique=True, verbose_name='Для кого')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Желтое золото', 'Желтое золото'), ('Розовое золото', 'Розовое золото'), ('Белое золото', 'Белое золото'), ('Платина', 'Платина'), ('Титан', 'Титан'), ('Сталь', 'Сталь'), ('Карбон', 'Карбон'), ('Керамика', 'Керамика'), ('Прочие материалы', 'Прочие материалы')], max_length=255, unique=True, verbose_name='Материал корпуса')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Овальная', 'Овальная'), ('Круглая', 'Круглая'), ('Квадратная', 'Квадратная'), ('Бочка', 'Бочка')], max_length=255, unique=True, verbose_name='Форма корпуса')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Grand комплектация', 'Grand комплектация'), ('Limited editions', 'Limited editions'), ('Special editions', 'Special editions'), ('Акция', 'Акция'), ('Новинка', 'Новинка'), ('Тюнинг', 'Тюнинг')], max_length=255, unique=True, verbose_name='Спецпредложения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название часов')),
                ('is_on_main', models.BooleanField(verbose_name='Выводить ли на главной?')),
                ('condition', models.CharField(choices=[('Идеальное', 'Идеальное'), ('Как новые', 'Как новые'), ('Коллекционное состояние', 'Коллекционное состояние'), ('Новые', 'Новые'), ('Отличное', 'Отличное'), ('Хорошее', 'Хорошее')], max_length=255, verbose_name='Состояние')),
                ('availability', models.CharField(choices=[('В наличии', 'В наличии'), ('Уточнить у менеджера', 'Уточнить у менеджера')], max_length=255, verbose_name='Наличие')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена часов')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('waterproof', models.CharField(max_length=255, verbose_name='Водонепроницаемость')),
                ('diameter', models.CharField(max_length=255, verbose_name='Диаметр корпуса')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет циферблата')),
                ('bezel', models.CharField(max_length=255, verbose_name='Безель')),
                ('mechanism', models.CharField(max_length=255, verbose_name='Механизм часов')),
                ('functions', models.CharField(max_length=255, verbose_name='Функции')),
                ('strap', models.CharField(max_length=255, verbose_name='Материал ремешка')),
                ('equipment', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('reference', models.CharField(max_length=255, verbose_name='Референсный номер')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.brand', verbose_name='Бренд')),
                ('for_who', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.forwho', verbose_name='Для кого')),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.material', verbose_name='Материал корпуса')),
                ('shape', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.shape', verbose_name='Форма корпуса')),
                ('special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.special', verbose_name='Спецпредложения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
