# Generated by Django 4.2 on 2024-05-14 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitychoice',
            options={'ordering': ['-id'], 'verbose_name': 'Наличие', 'verbose_name_plural': 'Наличие'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-title'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='conditionchoice',
            options={'ordering': ['-id'], 'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
        ),
        migrations.AlterModelOptions(
            name='forwho',
            options={'ordering': ['-title'], 'verbose_name': 'Для кого', 'verbose_name_plural': 'Для кого'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title'], 'verbose_name': 'Материал корпуса', 'verbose_name_plural': 'Материалы корпусов'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['-title'], 'verbose_name': 'Форма корпуса', 'verbose_name_plural': 'Формы корпусов'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['-title'], 'verbose_name': 'Спецпредложение', 'verbose_name_plural': 'Спецпредложения'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['-id'], 'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Необязательное поле, но очень желательное. Рекомендуемы размер: 400х400, формат: .webp', null=True, upload_to='watches_images'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='material',
            field=models.ForeignKey(default=1, help_text='Для фильтра на странице со списком часов.', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.material', verbose_name='Категория материала корпуса'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='material_alt',
            field=models.CharField(help_text='Для лучшего отображения на детальной странице часов. Обязательное поле.', max_length=255, verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Цена не может быть ниже 1')], verbose_name='Цена часов'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='waterproof',
            field=models.CharField(blank=True, help_text='Указывать в метрах. Например: "50 м". Необязательное поле.', max_length=255, null=True, verbose_name='Водонепроницаемость'),
        ),
    ]
