# Generated by Django 4.2 on 2024-05-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_watch_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='watches_images'),
        ),
    ]
