# Generated by Django 4.2 on 2024-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_watch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='watches_images'),
        ),
    ]
