# Generated by Django 4.2 on 2024-05-19 10:35

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models

import forms.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackWatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('communication_method', models.CharField(blank=True, choices=[('Звонок', 'Звонок'), ('На почту', 'На почту'), ('Telegram', 'Telegram'), ('WhatsUp', 'WhatsUp'), ('Viber', 'Viber')], max_length=255, null=True, verbose_name='Предпочитаемый способ связи')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('year', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='Значение года не может быть меньше 1900г.'), forms.validations.max_year_validator], verbose_name='Год покупки')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1.')], verbose_name='Желаемая сумма (руб.)')),
                ('condition', models.CharField(blank=True, choices=[('Идеальное', 'Идеальное'), ('Новое', 'Новое'), ('Естественные следы носки', 'Естественные следы носки'), ('Есть дефекты', 'Есть дефекты'), ('Требуется ремонт', 'Требуется ремонт')], max_length=255, null=True, verbose_name='Состояние часов')),
                ('equipment', models.CharField(blank=True, choices=[('С упаковкой', 'С упаковкой'), ('Без упаковки', 'Без упаковки')], max_length=255, null=True, verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Выкуп часов',
                'verbose_name_plural': 'Выкуп часов',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Заказ звонка',
                'verbose_name_plural': 'Заказы звонков',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('tags', models.CharField(choices=[('Общий вопрос', 'Общий вопрос'), ('Пожелания', 'Пожелания'), ('Обнаружена ошибка', 'Обнаружена ошибка')], max_length=255, verbose_name='Категория обращения')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ShortMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Малая форма',
                'verbose_name_plural': 'Малая форма',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ValuationWatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('communication_method', models.CharField(blank=True, choices=[('Звонок', 'Звонок'), ('На почту', 'На почту'), ('Telegram', 'Telegram'), ('WhatsUp', 'WhatsUp'), ('Viber', 'Viber')], max_length=255, null=True, verbose_name='Предпочитаемый способ связи')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('year', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='Значение года не может быть меньше 1900г.'), forms.validations.max_year_validator], verbose_name='Год покупки')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1.')], verbose_name='Желаемая сумма (руб.)')),
                ('condition', models.CharField(blank=True, choices=[('Идеальное', 'Идеальное'), ('Новое', 'Новое'), ('Естественные следы носки', 'Естественные следы носки'), ('Есть дефекты', 'Есть дефекты'), ('Требуется ремонт', 'Требуется ремонт')], max_length=255, null=True, verbose_name='Состояние часов')),
                ('equipment', models.CharField(blank=True, choices=[('С упаковкой', 'С упаковкой'), ('Без упаковки', 'Без упаковки')], max_length=255, null=True, verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Оценка часов',
                'verbose_name_plural': 'Оценка часов',
            },
        ),
        migrations.CreateModel(
            name='WatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('hiden_info', models.TextField(help_text='id: уникальный идентификатор часов; ref: уникальный референсный номер.', verbose_name='Данные запрашиваемых часов')),
            ],
            options={
                'verbose_name': 'Запрос на часы',
                'verbose_name_plural': 'Запросы на часы',
            },
        ),
        migrations.CreateModel(
            name='ValuationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='valuation_images')),
                ('valuation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val_images', to='forms.valuationwatches')),
            ],
            options={
                'verbose_name': 'Изображение из заявки на оценку',
                'verbose_name_plural': 'Изображения из заявок на оценку',
            },
        ),
        migrations.CreateModel(
            name='BuybackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buyback_images')),
                ('buyback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='forms.buybackwatches')),
            ],
            options={
                'verbose_name': 'Изображение из заявки',
                'verbose_name_plural': 'Изображения из заявок',
            },
        ),
    ]
