# Generated by Django 4.2 on 2024-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buybackimage',
            options={'verbose_name': 'Изображение из заявки', 'verbose_name_plural': 'Изображения из заявки'},
        ),
        migrations.AddField(
            model_name='call',
            name='processed',
            field=models.BooleanField(default=False, help_text='Обработан ли запрос?'),
        ),
    ]
