# Generated by Django 4.2 on 2024-05-13 06:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emai', models.EmailField(max_length=255, verbose_name='Почта')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
