# Generated by Django 4.2 on 2024-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_buybackimage_options_call_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
    ]
