# Generated by Django 4.2 on 2024-05-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_shortwithtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortWithText',
        ),
        migrations.AddField(
            model_name='shortmain',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
