# Generated by Django 4.2 on 2024-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_call_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackwatches',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
        migrations.AddField(
            model_name='shortmain',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
        migrations.AddField(
            model_name='valuationwatches',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
        migrations.AddField(
            model_name='watchrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли запрос'),
        ),
    ]
