# Generated by Django 4.2 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_buybackwatches_processed_feedback_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybackimage',
            name='image',
            field=models.ImageField(upload_to='buyback_images', verbose_name='Изображения часов из заявки на выкуп'),
        ),
        migrations.AlterField(
            model_name='buybackwatches',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
        migrations.AlterField(
            model_name='call',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
        migrations.AlterField(
            model_name='shortmain',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
        migrations.AlterField(
            model_name='valuationimage',
            name='image',
            field=models.ImageField(upload_to='valuation_images', verbose_name='Изображения часов из заявки на оценку'),
        ),
        migrations.AlterField(
            model_name='valuationwatches',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
        migrations.AlterField(
            model_name='watchrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
    ]
