# Generated by Django 4.2 on 2024-05-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shortmain',
            old_name='emai',
            new_name='email',
        ),
    ]
