# Generated by Django 4.2 on 2024-05-13 11:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_rename_emai_feedback_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('name', models.CharField(max_length=56, verbose_name='Имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('text', models.TextField()),
                ('communication_method', models.CharField(choices=[('Звонок', 'Звонок'), ('На почту', 'На почту'), ('Telegram', 'Telegram'), ('WhatsUp', 'WhatsUp'), ('Viber', 'Viber')], max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.SmallIntegerField()),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('Идеальное', 'Идеальное'), ('Новое', 'Новое'), ('Естественные следы носки', 'Естественные следы носки'), ('Есть дефекты', 'Есть дефекты'), ('Требуется ремонт', 'Требуется ремонт')], max_length=255)),
                ('equipment', models.CharField(choices=[('С упаковкой', 'С упаковкой'), ('Без упаковки', 'Без упаковки')], max_length=255)),
                ('images', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
