# Generated by Django 4.2 on 2024-05-14 11:58

import django.core.validators
from django.db import migrations, models
import forms.validations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_watchrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buybackwatch',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Выкуп часов', 'verbose_name_plural': 'Выкуп часов'},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Заказ звонка', 'verbose_name_plural': 'Заказы звонков'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='shortmain',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Малая форма', 'verbose_name_plural': 'Малая форма'},
        ),
        migrations.AlterModelOptions(
            name='watchrequest',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Запрос на часы', 'verbose_name_plural': 'Запросы на часы'},
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('Звонок', 'Звонок'), ('На почту', 'На почту'), ('Telegram', 'Telegram'), ('WhatsUp', 'WhatsUp'), ('Viber', 'Viber')], max_length=255, null=True, verbose_name='Предпочитаемый способ связи'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='condition',
            field=models.CharField(blank=True, choices=[('Идеальное', 'Идеальное'), ('Новое', 'Новое'), ('Естественные следы носки', 'Естественные следы носки'), ('Есть дефекты', 'Есть дефекты'), ('Требуется ремонт', 'Требуется ремонт')], max_length=255, null=True, verbose_name='Состояние часов'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='equipment',
            field=models.CharField(blank=True, choices=[('С упаковкой', 'С упаковкой'), ('Без упаковки', 'Без упаковки')], max_length=255, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='images',
            field=models.FileField(upload_to='buyback_images', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1.')], verbose_name='Желаемая сумма (руб.)'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='buybackwatch',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='Значение года не может быть меньше 1900г.'), forms.validations.max_year_validator], verbose_name='Год покупки'),
        ),
        migrations.AlterField(
            model_name='call',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='call',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tags',
            field=models.CharField(choices=[('Общий вопрос', 'Общий вопрос'), ('Пожелания', 'Пожелания'), ('Обнаружена ошибка', 'Обнаружена ошибка')], max_length=255, verbose_name='Категория обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='shortmain',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='shortmain',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='watchrequest',
            name='hiden_info',
            field=models.TextField(help_text='id: уникальный идентификатор часов; ref: уникальный референсный номер.', verbose_name='Данные запрашиваемых часов'),
        ),
        migrations.AlterField(
            model_name='watchrequest',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='watchrequest',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
