# Generated by Django 4.2 on 2024-05-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_buybackwatch_options_alter_call_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buyback_images')),
                ('buyback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches_images', to='forms.buybackwatch')),
            ],
        ),
    ]
