# Generated by Django 4.2 on 2024-05-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_buybackimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybackwatch',
            name='images',
        ),
    ]
