# Generated by Django 4.2 on 2024-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_buybackwatch_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackwatch',
            name='images',
            field=models.FileField(default=1, upload_to='buyback_images', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
