# Generated by Django 4.2 on 2024-05-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_buybackwatch_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybackwatch',
            name='images',
        ),
        migrations.AlterField(
            model_name='buybackimage',
            name='buyback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='forms.buybackwatch'),
        ),
    ]
